# Generated by Django 4.2.3 on 2023-07-28 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_statistics', '0002_rename_player_name_timestatistics_player_identifier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timestatistics',
            name='player_identifier',
        ),
    ]
